[package]
name = "smart_cam"
version = "0.1.0"
edition = "2021"

[dependencies]
camera_capture={path="../camera_capture"}
motion_detection={path="../motion_detection"}
tokio = {workspace=true}
tokio-util = {workspace=true}
# use workspace version of log
log = {workspace=true}